CREATE TABLE chatter_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

ALTER TABLE chatter_child
  ADD COLUMN
    parent_id INTEGER REFERENCES chatter_users(id)
    ON DELETE SET NULL;